export const data = [
  {
    id: 1831487,
    name: 'Jahnu Gill',
    email: 'jahnu_gill@lindgren.example',
    gender: 'female',
    status: 'active',
  },
  {
    id: 1831486,
    name: 'Charvi Gandhi',
    email: 'charvi_gandhi@lueilwitz.example',
    gender: 'female',
    status: 'inactive',
  },
  {
    id: 1831483,
    name: 'Chandraswaroopa Dwivedi II',
    email: 'dwivedi_ii_chandraswaroopa@kuhlman-koss.test',
    gender: 'male',
    status: 'inactive',
  },
  {
    id: 1831482,
    name: 'Divya Ahuja DDS',
    email: 'dds_ahuja_divya@kuhn-willms.example',
    gender: 'female',
    status: 'active',
  },
  {
    id: 1831481,
    name: 'Miss Vinay Joshi',
    email: 'joshi_miss_vinay@crooks-runolfsson.example',
    gender: 'female',
    status: 'active',
  },
  {
    id: 1831480,
    name: 'Sudeva Joshi',
    email: 'joshi_sudeva@jerde.test',
    gender: 'female',
    status: 'active',
  },
  {
    id: 1831479,
    name: 'Ms. Navin Ahluwalia',
    email: 'navin_ahluwalia_ms@kreiger.test',
    gender: 'male',
    status: 'active',
  },
  {
    id: 1831478,
    name: 'Himadri Jain',
    email: 'himadri_jain@mertz.test',
    gender: 'male',
    status: 'active',
  },
  {
    id: 1831477,
    name: 'Adityanandan Malik',
    email: 'adityanandan_malik@kuhic.test',
    gender: 'male',
    status: 'active',
  },
  {
    id: 1831476,
    name: 'Achalesvara Acharya II',
    email: 'ii_achalesvara_acharya@reichert.test',
    gender: 'male',
    status: 'inactive',
  },
]
